### ISSUE TITLE
思路是什么？

### ISSUE THREAD

**Issue by kunlongxu** [ustbhuangyi/animation#7]
在幕课的课程我也看了，很是崇拜您，无论是从编程风格还是技术异或编程思想，但是这课我看完了感觉很迷惑，特别是里面的
* 同步方法
* 异步方法
* 时间轴

这三块的思路，还是不清楚，如果老师有时间，还请指点一下，实在不行，我也要再撸几遍！！！

**Comment by ustbhuangyi** [comment]
其实就是利用了类似 promise 的思想，把异步操作也通过链式调用的方式实现，为了让调用方更加爽，这门课录制没有实时调试预览，所以不是很容易理解，最好多看几遍，会有收获。
